### ISSUE TITLE
Make post request to upload file in postman

### ISSUE THREAD

**Issue by minhnbwork97** [moodlehq/sample-ws-clients#11]
Can I make post request to upload file in postman?
![Screen Shot 2020-01-16 at 17 19 53](https://user-images.githubusercontent.com/38205529/72516570-78198b80-3884-11ea-9b0b-edc273d22cbd.png)
I'm trying to upload file from my computer but I think the value of file_1 is incorrect.
How do I get the correct path of the file from my computer?

**Comment by NoelDeMartin** [comment]
To send a file using postman you should use the Body tab and select the "File" type: 
![image](https://user-images.githubusercontent.com/1517677/72521665-252bde00-385c-11ea-9a97-db1d229d8a9d.png)

**Comment by minhnbwork97** [comment]
Wow thank you @NoelDeMartin . That works.
But is there anyway I can find the path to my file like this (https://github.com/moodlehq/sample-ws-clients/blob/master/PHP-HTTP-filehandling/client.php - line 27)?
<img width="806" alt="Screen Shot 2020-01-17 at 08 25 42" src="https://user-images.githubusercontent.com/38205529/72576737-1cdaae00-3903-11ea-92cd-a37fd9bbc862.png">

**Comment by minhnbwork97** [comment]
I found this, perfectly suite my case cause I'm using javascript. Problem solved. 
![image](https://user-images.githubusercontent.com/38205529/72579547-fbca8b00-390b-11ea-8721-61f88c21d26a.png)

**Comment by NoelDeMartin** [comment]
Cool, glad to help :)
